-- Etta AI Agent tables (generated by prisma migrate diff)

-- CreateTable
CREATE TABLE "etta_actors" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "actor_type" TEXT NOT NULL DEFAULT 'etta',
    "permissions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "provisioned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_active_at" TIMESTAMP(3),
    "revoked_at" TIMESTAMP(3),

    CONSTRAINT "etta_actors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "etta_suggestions" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "actor_id" TEXT NOT NULL,
    "action_type" TEXT NOT NULL,
    "tier" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "summary" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "chat_message_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolved_at" TIMESTAMP(3),
    "resolved_by" TEXT,

    CONSTRAINT "etta_suggestions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "etta_memory" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "etta_memory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_log" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "actor_id" TEXT NOT NULL,
    "actor_type" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "resource_type" TEXT NOT NULL,
    "resource_id" TEXT,
    "tier" TEXT,
    "payload_snapshot" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "guest_questions" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "guest_id" INTEGER NOT NULL,
    "question" TEXT NOT NULL,
    "context" TEXT,
    "answered" BOOLEAN NOT NULL DEFAULT false,
    "answer" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "answered_at" TIMESTAMP(3),

    CONSTRAINT "guest_questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "faqs" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "faqs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "wedding_id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "etta_actors_wedding_id_key" ON "etta_actors"("wedding_id");

-- CreateIndex
CREATE INDEX "etta_suggestions_wedding_id_status_idx" ON "etta_suggestions"("wedding_id", "status");

-- CreateIndex
CREATE INDEX "etta_suggestions_created_at_idx" ON "etta_suggestions"("created_at" DESC);

-- CreateIndex
CREATE INDEX "etta_memory_wedding_id_idx" ON "etta_memory"("wedding_id");

-- CreateIndex
CREATE INDEX "audit_log_wedding_id_created_at_idx" ON "audit_log"("wedding_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_log_actor_id_idx" ON "audit_log"("actor_id");

-- CreateIndex
CREATE INDEX "guest_questions_wedding_id_answered_idx" ON "guest_questions"("wedding_id", "answered");

-- CreateIndex
CREATE INDEX "faqs_wedding_id_published_idx" ON "faqs"("wedding_id", "published");

-- CreateIndex
CREATE INDEX "notifications_wedding_id_read_idx" ON "notifications"("wedding_id", "read");

-- AddForeignKey
ALTER TABLE "etta_actors" ADD CONSTRAINT "etta_actors_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "etta_suggestions" ADD CONSTRAINT "etta_suggestions_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "etta_suggestions" ADD CONSTRAINT "etta_suggestions_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "etta_actors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "etta_memory" ADD CONSTRAINT "etta_memory_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "guest_questions" ADD CONSTRAINT "guest_questions_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "guest_questions" ADD CONSTRAINT "guest_questions_guest_id_fkey" FOREIGN KEY ("guest_id") REFERENCES "Guest"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "faqs" ADD CONSTRAINT "faqs_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_wedding_id_fkey" FOREIGN KEY ("wedding_id") REFERENCES "Wedding"("id") ON DELETE CASCADE ON UPDATE CASCADE;
