name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for your idea.
      options:
        - label: I have searched the existing issues and this is a new feature request
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches have you thought about?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the application does this feature relate to?
      options:
        - Guest Management
        - RSVP System
        - Wedding Website
        - Dashboard/Analytics
        - Authentication
        - API/Backend
        - UI/UX
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical/Blocking
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other applications.
      placeholder: Drag and drop images here or paste links

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here.
      placeholder: Any additional information that might help us understand your request...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/dccakes/SCV/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
